<?xml version="1.0" encoding="utf-8"?><Database Name="SOFTPETI" Class="DataClasses3DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=SOFTPETI;Integrated Security=True;Connect Timeout=30;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="WindowsFormsApp2.Properties.Settings" SettingsPropertyName="SOFTPETIConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Vision" Member="Vision">
    <Type Name="Vision">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usuario_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="USUARIO_Vision" Member="USUARIO" ThisKey="usuario_id" OtherKey="id" Type="USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.USUARIO" Member="USUARIO">
    <Type Name="USUARIO">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="password_hash" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Association Name="USUARIO_Vision" Member="Vision" ThisKey="id" OtherKey="usuario_id" Type="Vision" />
      <Association Name="USUARIO_Mision" Member="Mision" ThisKey="id" OtherKey="usuario_id" Type="Mision" />
      <Association Name="USUARIO_Empresa" Member="Empresa" ThisKey="id" OtherKey="usuario_id" Type="Empresa" />
    </Type>
  </Table>
  <Table Name="dbo.Mision" Member="Mision">
    <Type Name="Mision">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usuario_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="USUARIO_Mision" Member="USUARIO" ThisKey="usuario_id" OtherKey="id" Type="USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Empresa" Member="Empresa">
    <Type Name="Empresa">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="usuario_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="USUARIO_Empresa" Member="USUARIO" ThisKey="usuario_id" OtherKey="id" Type="USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_Autenticar" Method="SP_Autenticar">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PasswordHash" Parameter="passwordHash" Type="System.String" DbType="VarChar(64)" />
    <ElementType Name="SP_AutenticarResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarEmpresasPorUsuario" Method="SP_ListarEmpresasPorUsuario">
    <Parameter Name="usuario_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarEmpresasPorUsuarioResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_RegistrarEmpresa" Method="SP_RegistrarEmpresa">
    <Parameter Name="nombre" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="usuario_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_RegistrarMision" Method="SP_RegistrarMision">
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="usuario_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_RegistrarVision" Method="SP_RegistrarVision">
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="usuario_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarMisionPorUsuarioYEmpresa" Method="SP_ListarMisionPorUsuarioYEmpresa">
    <Parameter Name="UsuarioId" Parameter="usuarioId" Type="System.Int32" DbType="Int" />
    <Parameter Name="EmpresaId" Parameter="empresaId" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarMisionPorUsuarioYEmpresaResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usuario_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarVisionPorUsuarioYEmpresa" Method="SP_ListarVisionPorUsuarioYEmpresa">
    <Parameter Name="UsuarioId" Parameter="usuarioId" Type="System.Int32" DbType="Int" />
    <Parameter Name="EmpresaId" Parameter="empresaId" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarVisionPorUsuarioYEmpresaResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usuario_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_RegistrarValores" Method="SP_RegistrarValores">
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="usuario_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>